import { ElementsClipboard } from '../../../clipboard'

const obj: ElementsClipboard = {
  type: 'excalidraw/clipboard',
  elements: [
    {
      type: 'rectangle',
      version: 21,
      versionNonce: 1226616923,
      isDeleted: false,
      id: 'VwkyPxnXBKahGNqdn2psX',
      fillStyle: 'solid',
      strokeWidth: 1,
      strokeStyle: 'solid',
      roughness: 0,
      opacity: 100,
      angle: 0,
      x: 1680,
      y: -220,
      strokeColor: '#1e1e1e',
      backgroundColor: '#e9ecef',
      width: 120,
      height: 60,
      seed: 2235131,
      groupIds: ['PY-6qpUMF0SPZAtJa6u4r', 'rM6mywrObOre1AikZoh0W'],
      frameId: null,
      roundness: null,
      boundElements: [],
      updated: 1707073011628,
      link: null,
      locked: false,
      customData: { kind: 'Prop', id: '', elementIds: [], elements: [], name: 'Square Table' },
    },
    {
      id: 'NeTshwegFaz-KycZWrA7W',
      type: 'line',
      x: 1680,
      y: -180,
      width: 120,
      height: 0,
      angle: 0,
      strokeColor: '#1e1e1e',
      backgroundColor: '#ffd43b',
      fillStyle: 'hachure',
      strokeWidth: 1,
      strokeStyle: 'solid',
      roughness: 0,
      opacity: 100,
      groupIds: ['rM6mywrObOre1AikZoh0W'],
      frameId: null,
      roundness: null,
      seed: 464736533,
      version: 28,
      versionNonce: 1753831125,
      isDeleted: false,
      boundElements: null,
      updated: 1707073011628,
      link: null,
      locked: false,
      points: [
        [0, 0],
        [120, 0],
      ],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: null,
    },
    {
      type: 'line',
      version: 41,
      versionNonce: 1081863419,
      isDeleted: false,
      id: '_SPCajr_O922J3h-LzRSl',
      fillStyle: 'hachure',
      strokeWidth: 1,
      strokeStyle: 'dotted',
      roughness: 0,
      opacity: 100,
      angle: 0,
      x: 1680,
      y: -170,
      strokeColor: '#1e1e1e',
      backgroundColor: '#ffd43b',
      width: 120,
      height: 0,
      seed: 346685173,
      groupIds: ['rM6mywrObOre1AikZoh0W'],
      frameId: null,
      roundness: null,
      boundElements: [],
      updated: 1707073011628,
      link: null,
      locked: false,
      startBinding: null,
      endBinding: null,
      lastCommittedPoint: null,
      startArrowhead: null,
      endArrowhead: null,
      points: [
        [0, 0],
        [120, 0],
      ],
    },
  ],
  files: {},
}
export default obj
